/* src/Constants/actionTypes.js */

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_PENDING = 'FETCH_COMMENT_PENDING';
export const FETCH_COMMENT_REJECTED = 'FETCH_COMMENT_REJECTED';
export const FETCH_COMMENT_FULLFILLED = 'FETCH_COMMENT_FULLFILLED';
