/* src/Constants/actionTypes.js */

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_FULFILLED = 'FETCH_COMMENT_FULFILLED';
export const FETCH_COMMENT_PENDING = 'FETCH_COMMENT_PENDING';
export const FETCH_COMMENT_REJECTED = 'FETCH_COMMENT_REJECTED';

export const FETCH_POST_PENDING = 'FETCH_POST_PENDING';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export const FETCH_TODO_PENDING = 'FETCH_TODO_PENDING';
export const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE';
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
